# Generated by Django 5.2.3 on 2025-06-30 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_veterinario_user_alter_cirugia_veterinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='clinica.consulta')),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.dueno')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.mascota')),
                ('medicamentos', models.ManyToManyField(blank=True, to='clinica.medicamento')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.veterinario')),
            ],
        ),
    ]
